import type pg from "pg"

/**
 * Static registry of board services (26 AI + Cloud / Developer / Data /
 * Auth / Payments / Observability Waves A–C + Email Waves A–C +
 * Design Waves A–C + Infra Waves A–C + Flags Waves A–B).
 * Mirrors the ids in the Next.js app's data/services.ts (and public/logos/{id}.svg).
 * Windsurf is the legacy Devin Desktop name and is not seeded separately.
 * GitHub Copilot is a GitHub component, not its own card.
 *
 * `category` defaults to `ai` when omitted. AWS, Azure, Fastly, Replit,
 * Redis, Algolia, DataStax, Okta, PayPal, Adyen, PagerDuty, Checkly,
 * Postmark, Mailchimp, Campaign Monitor, Mailtrap, Substack, Adobe,
 * Sketch, Penpot, Rive, LottieFiles, Whimsical, Lunacy, Photopea,
 * Blender, Moqups, Proto.io, UXPin, Overflow, Axure, Relume, Visily,
 * Plasmic, OpenTofu, Ansible, Argo CD, Flux, Terragrunt, Env0, Salt,
 * Rancher, Vagrant, Helm, Istio, Linkerd, Cilium, OPA, Kyverno,
 * Traefik, cert-manager, Infracost, Unleash, ConfigCat, GrowthBook,
 * Eppo, VWO, AB Tasty, Convert, Flipt, Hypertune, GO Feature Flag,
 * and FeatBit are `none` until a dedicated fetcher exists.
 */
export const SERVICE_SEED = [
  {
    id: "openai",
    name: "OpenAI",
    statusUrl: "https://status.openai.com/",
    fetcherType: "statuspage",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    statusUrl: "https://status.claude.com/",
    fetcherType: "statuspage",
  },
  {
    id: "google-gemini",
    name: "Google Gemini",
    statusUrl: "https://aistudio.google.com/status",
    fetcherType: "google_cloud",
  },
  { id: "xai", name: "xAI", statusUrl: "https://status.x.ai/", fetcherType: "rss" },
  {
    id: "mistral",
    name: "Mistral",
    statusUrl: "https://status.mistral.ai/",
    fetcherType: "checkly_nuxt",
  },
  { id: "groq", name: "Groq", statusUrl: "https://groqstatus.com/", fetcherType: "statuspage" },
  {
    id: "perplexity",
    name: "Perplexity",
    statusUrl: "https://status.perplexity.com/",
    fetcherType: "instatus",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    statusUrl: "https://status.deepseek.com/",
    fetcherType: "rss",
  },
  {
    id: "cohere",
    name: "Cohere",
    statusUrl: "https://status.cohere.com/",
    fetcherType: "statuspage",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    statusUrl: "https://status.openrouter.ai/",
    fetcherType: "onlineornot",
  },
  {
    id: "fireworks",
    name: "Fireworks AI",
    statusUrl: "https://status.fireworks.ai/",
    fetcherType: "statuspage",
  },
  {
    id: "together",
    name: "Together AI",
    statusUrl: "https://status.together.ai/",
    fetcherType: "betterstack",
  },
  {
    id: "cerebras",
    name: "Cerebras",
    statusUrl: "https://status.cerebras.ai/",
    fetcherType: "statuspage",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    statusUrl: "https://status.huggingface.co/",
    fetcherType: "betterstack",
  },
  {
    id: "replicate",
    name: "Replicate",
    statusUrl: "https://status.replicate.com/",
    fetcherType: "statuspage",
  },
  {
    id: "runway",
    name: "Runway",
    statusUrl: "https://status.runwayml.com/",
    fetcherType: "statuspage",
  },
  {
    id: "ideogram",
    name: "Ideogram",
    statusUrl: "https://status.ideogram.ai/",
    fetcherType: "statuspage",
  },
  {
    id: "stability",
    name: "Stability AI",
    statusUrl: "https://status.stability.ai/",
    fetcherType: "statuspage",
  },
  {
    id: "fal",
    name: "fal",
    statusUrl: "https://status.fal.ai/",
    fetcherType: "instatus",
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    statusUrl: "https://status.elevenlabs.io/",
    fetcherType: "statuspage",
  },
  {
    id: "minimax",
    name: "MiniMax",
    statusUrl: "https://status.minimax.io/",
    fetcherType: "statuspage",
  },
  {
    id: "voyage",
    name: "Voyage AI",
    statusUrl: "https://status.voyageai.com/",
    fetcherType: "statuspage",
  },
  {
    id: "bfl",
    name: "Black Forest Labs",
    statusUrl: "https://status.bfl.ml/",
    fetcherType: "statuspage",
  },
  {
    id: "cartesia",
    name: "Cartesia",
    statusUrl: "https://status.cartesia.ai/",
    fetcherType: "statuspage",
  },
  {
    id: "kimi",
    name: "Kimi",
    statusUrl: "https://status.moonshot.cn/",
    fetcherType: "statuspage",
  },
  {
    id: "luma",
    name: "Luma",
    statusUrl: "https://status.lumalabs.ai/",
    fetcherType: "betterstack",
  },
  {
    id: "vercel",
    name: "Vercel",
    category: "cloud",
    statusUrl: "https://www.vercel-status.com/",
    fetcherType: "statuspage",
  },
  {
    id: "railway",
    name: "Railway",
    category: "cloud",
    statusUrl: "https://status.railway.com/",
    fetcherType: "railway",
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    category: "cloud",
    statusUrl: "https://www.cloudflarestatus.com/",
    fetcherType: "statuspage",
  },
  {
    id: "render",
    name: "Render",
    category: "cloud",
    statusUrl: "https://status.render.com/",
    fetcherType: "statuspage",
  },
  {
    id: "fly",
    name: "Fly.io",
    category: "cloud",
    statusUrl: "https://status.flyio.net/",
    fetcherType: "statuspage",
  },
  {
    id: "netlify",
    name: "Netlify",
    category: "cloud",
    statusUrl: "https://www.netlifystatus.com/",
    fetcherType: "statuspage",
  },
  {
    id: "digitalocean",
    name: "DigitalOcean",
    category: "cloud",
    statusUrl: "https://status.digitalocean.com/",
    fetcherType: "statuspage",
  },
  {
    id: "google-cloud",
    name: "Google Cloud",
    category: "cloud",
    statusUrl: "https://status.cloud.google.com/",
    fetcherType: "google_cloud",
  },
  {
    id: "aws",
    name: "AWS",
    category: "cloud",
    statusUrl: "https://health.aws.amazon.com/health/status",
    fetcherType: "none",
  },
  {
    id: "azure",
    name: "Azure",
    category: "cloud",
    statusUrl: "https://azure.microsoft.com/status/",
    fetcherType: "none",
  },
  {
    id: "heroku",
    name: "Heroku",
    category: "cloud",
    statusUrl: "https://status.salesforce.com/products/Heroku",
    fetcherType: "heroku",
  },
  {
    id: "linode",
    name: "Linode",
    category: "cloud",
    statusUrl: "https://status.linode.com/",
    fetcherType: "statuspage",
  },
  {
    id: "fastly",
    name: "Fastly",
    category: "cloud",
    statusUrl: "https://www.fastlystatus.com/",
    fetcherType: "none",
  },
  {
    id: "bunny",
    name: "bunny.net",
    category: "cloud",
    statusUrl: "https://status.bunny.net/",
    fetcherType: "statuspage",
  },
  {
    id: "deno",
    name: "Deno Deploy",
    category: "cloud",
    statusUrl: "https://denostatus.com/",
    fetcherType: "instatus",
  },
  {
    id: "koyeb",
    name: "Koyeb",
    category: "cloud",
    statusUrl: "https://status.koyeb.com/",
    fetcherType: "instatus",
  },
  {
    id: "modal",
    name: "Modal",
    category: "cloud",
    statusUrl: "https://status.modal.com/",
    fetcherType: "betterstack",
  },
  {
    id: "firebase",
    name: "Firebase",
    category: "cloud",
    statusUrl: "https://status.firebase.google.com/",
    fetcherType: "google_cloud",
  },
  {
    id: "akamai",
    name: "Akamai",
    category: "cloud",
    statusUrl: "https://www.akamaistatus.com/",
    fetcherType: "statuspage",
  },
  {
    id: "vultr",
    name: "Vultr",
    category: "cloud",
    statusUrl: "https://status.vultr.com/",
    fetcherType: "vultr",
  },
  {
    id: "scaleway",
    name: "Scaleway",
    category: "cloud",
    statusUrl: "https://status.scaleway.com/",
    fetcherType: "statuspage",
  },
  {
    id: "oracle-cloud",
    name: "Oracle Cloud",
    category: "cloud",
    statusUrl: "https://ocistatus.oraclecloud.com/",
    fetcherType: "oracle_cloud",
  },
  {
    id: "hetzner",
    name: "Hetzner",
    category: "cloud",
    statusUrl: "https://status.hetzner.com/",
    fetcherType: "hetzner",
  },
  {
    id: "northflank",
    name: "Northflank",
    category: "cloud",
    statusUrl: "https://status.northflank.com/",
    fetcherType: "instatus",
  },
  {
    id: "lambda",
    name: "Lambda",
    category: "cloud",
    statusUrl: "https://status.lambda.ai/",
    fetcherType: "statuspage",
  },
  {
    id: "cursor",
    name: "Cursor",
    category: "developer",
    statusUrl: "https://status.cursor.com/",
    fetcherType: "statuspage",
  },
  {
    id: "devin",
    name: "Devin",
    category: "developer",
    statusUrl: "https://status.devin.ai/",
    fetcherType: "statuspage",
  },
  {
    id: "github",
    name: "GitHub",
    category: "developer",
    statusUrl: "https://www.githubstatus.com/",
    fetcherType: "statuspage",
  },
  {
    id: "gitlab",
    name: "GitLab",
    category: "developer",
    statusUrl: "https://status.gitlab.com/",
    fetcherType: "status_io",
  },
  {
    id: "circleci",
    name: "CircleCI",
    category: "developer",
    statusUrl: "https://status.circleci.com/",
    fetcherType: "statuspage",
  },
  {
    id: "npm",
    name: "npm",
    category: "developer",
    statusUrl: "https://status.npmjs.org/",
    fetcherType: "statuspage",
  },
  {
    id: "docker",
    name: "Docker",
    category: "developer",
    statusUrl: "https://www.dockerstatus.com/",
    fetcherType: "statuspage",
  },
  {
    id: "linear",
    name: "Linear",
    category: "developer",
    statusUrl: "https://linearstatus.com/",
    fetcherType: "statuspage",
  },
  {
    id: "sourcegraph",
    name: "Sourcegraph",
    category: "developer",
    statusUrl: "https://sourcegraphstatus.com/",
    fetcherType: "statuspage",
  },
  {
    id: "warp",
    name: "Warp",
    category: "developer",
    statusUrl: "https://status.warp.dev/",
    fetcherType: "statuspage",
  },
  {
    id: "bitbucket",
    name: "Bitbucket",
    category: "developer",
    statusUrl: "https://bitbucket.status.atlassian.com/",
    fetcherType: "statuspage",
  },
  {
    id: "buildkite",
    name: "Buildkite",
    category: "developer",
    statusUrl: "https://www.buildkitestatus.com/",
    fetcherType: "statuspage",
  },
  {
    id: "pypi",
    name: "PyPI",
    category: "developer",
    statusUrl: "https://status.python.org/",
    fetcherType: "statuspage",
  },
  {
    id: "rubygems",
    name: "RubyGems",
    category: "developer",
    statusUrl: "https://status.rubygems.org/",
    fetcherType: "statuspage",
  },
  {
    id: "maven",
    name: "Maven Central",
    category: "developer",
    statusUrl: "https://status.maven.org/",
    fetcherType: "statuspage",
  },
  {
    id: "postman",
    name: "Postman",
    category: "developer",
    statusUrl: "https://status.postman.com/",
    fetcherType: "statuspage",
  },
  {
    id: "augment",
    name: "Augment",
    category: "developer",
    statusUrl: "https://status.augmentcode.com/",
    fetcherType: "statuspage",
  },
  {
    id: "factory",
    name: "Factory",
    category: "developer",
    statusUrl: "https://status.factory.ai/",
    fetcherType: "statuspage",
  },
  {
    id: "tabnine",
    name: "Tabnine",
    category: "developer",
    statusUrl: "https://status.tabnine.com/",
    fetcherType: "statuspage",
  },
  {
    id: "zed",
    name: "Zed",
    category: "developer",
    statusUrl: "https://status.zed.dev/",
    fetcherType: "instatus",
  },
  {
    id: "lovable",
    name: "Lovable",
    category: "developer",
    statusUrl: "https://status.lovable.dev/",
    fetcherType: "statuspage",
  },
  {
    id: "bolt",
    name: "Bolt",
    category: "developer",
    statusUrl: "https://status.bolt.new/",
    fetcherType: "statuspage",
  },
  {
    id: "replit",
    name: "Replit",
    category: "developer",
    statusUrl: "https://status.replit.com/",
    fetcherType: "none",
  },
  {
    id: "travis",
    name: "Travis CI",
    category: "developer",
    statusUrl: "https://www.traviscistatus.com/",
    fetcherType: "statuspage",
  },
  {
    id: "semaphore",
    name: "Semaphore",
    category: "developer",
    statusUrl: "https://status.semaphore.io/",
    fetcherType: "statuspage",
  },
  {
    id: "harness",
    name: "Harness",
    category: "developer",
    statusUrl: "https://status.harness.io/",
    fetcherType: "statuspage",
  },
  {
    id: "codefresh",
    name: "Codefresh",
    category: "developer",
    statusUrl: "https://status.codefresh.io/",
    fetcherType: "statuspage",
  },
  {
    id: "crates",
    name: "crates.io",
    category: "developer",
    statusUrl: "https://status.crates.io/",
    fetcherType: "statuspage",
  },
  {
    id: "expo",
    name: "Expo",
    category: "developer",
    statusUrl: "https://status.expo.dev/",
    fetcherType: "statuspage",
  },
  {
    id: "cloudsmith",
    name: "Cloudsmith",
    category: "developer",
    statusUrl: "https://status.cloudsmith.com/",
    fetcherType: "statuspage",
  },
  {
    id: "supabase",
    name: "Supabase",
    category: "data",
    statusUrl: "https://status.supabase.com/",
    fetcherType: "statuspage",
  },
  {
    id: "neon",
    name: "Neon",
    category: "data",
    statusUrl: "https://neonstatus.com/",
    fetcherType: "status_io",
  },
  {
    id: "planetscale",
    name: "PlanetScale",
    category: "data",
    statusUrl: "https://www.planetscalestatus.com/",
    fetcherType: "statuspage",
  },
  {
    id: "convex",
    name: "Convex",
    category: "data",
    statusUrl: "https://status.convex.dev/",
    fetcherType: "statuspage",
  },
  {
    id: "upstash",
    name: "Upstash",
    category: "data",
    statusUrl: "https://status.upstash.com/",
    fetcherType: "statuspage",
  },
  {
    id: "redis",
    name: "Redis",
    category: "data",
    statusUrl: "https://status.redis.io/",
    fetcherType: "none",
  },
  {
    id: "pinecone",
    name: "Pinecone",
    category: "data",
    statusUrl: "https://status.pinecone.io/",
    fetcherType: "statuspage",
  },
  {
    id: "mongodb",
    name: "MongoDB",
    category: "data",
    statusUrl: "https://status.mongodb.com/",
    fetcherType: "statuspage",
  },
  {
    id: "cockroach",
    name: "CockroachDB",
    category: "data",
    statusUrl: "https://status.cockroachlabs.cloud/",
    fetcherType: "statuspage",
  },
  {
    id: "prisma",
    name: "Prisma",
    category: "data",
    statusUrl: "https://www.prisma-status.com/",
    fetcherType: "statuspage",
  },
  {
    id: "snowflake",
    name: "Snowflake",
    category: "data",
    statusUrl: "https://status.snowflake.com/",
    fetcherType: "statuspage",
  },
  {
    id: "databricks",
    name: "Databricks",
    category: "data",
    statusUrl: "https://status.databricks.com/",
    fetcherType: "status_io",
  },
  {
    id: "clickhouse",
    name: "ClickHouse",
    category: "data",
    statusUrl: "https://status.clickhouse.com/",
    fetcherType: "statuspage",
  },
  {
    id: "elastic",
    name: "Elastic",
    category: "data",
    statusUrl: "https://status.elastic.co/",
    fetcherType: "statuspage",
  },
  {
    id: "aiven",
    name: "Aiven",
    category: "data",
    statusUrl: "https://status.aiven.io/",
    fetcherType: "statuspage",
  },
  {
    id: "influxdb",
    name: "InfluxDB",
    category: "data",
    statusUrl: "https://status.influxdata.com/",
    fetcherType: "statuspage",
  },
  {
    id: "couchbase",
    name: "Couchbase",
    category: "data",
    statusUrl: "https://status.couchbase.com/",
    fetcherType: "statuspage",
  },
  {
    id: "confluent",
    name: "Confluent",
    category: "data",
    statusUrl: "https://status.confluent.cloud/",
    fetcherType: "statuspage",
  },
  {
    id: "tinybird",
    name: "Tinybird",
    category: "data",
    statusUrl: "https://status.tinybird.co/",
    fetcherType: "statuspage",
  },
  {
    id: "zilliz",
    name: "Zilliz",
    category: "data",
    statusUrl: "https://status.zilliz.com/",
    fetcherType: "statuspage",
  },
  {
    id: "materialize",
    name: "Materialize",
    category: "data",
    statusUrl: "https://status.materialize.com/",
    fetcherType: "statuspage",
  },
  {
    id: "turso",
    name: "Turso",
    category: "data",
    statusUrl: "https://status.turso.tech/",
    fetcherType: "betterstack",
  },
  {
    id: "qdrant",
    name: "Qdrant",
    category: "data",
    statusUrl: "https://status.qdrant.io/",
    fetcherType: "betterstack",
  },
  {
    id: "meilisearch",
    name: "Meilisearch",
    category: "data",
    statusUrl: "https://status.meilisearch.com/",
    fetcherType: "betterstack",
  },
  {
    id: "algolia",
    name: "Algolia",
    category: "data",
    statusUrl: "https://status.algolia.com/",
    fetcherType: "none",
  },
  {
    id: "redpanda",
    name: "Redpanda",
    category: "data",
    statusUrl: "https://status.redpanda.com/",
    fetcherType: "statuspage",
  },
  {
    id: "surreal",
    name: "SurrealDB",
    category: "data",
    statusUrl: "https://status.surrealdb.com/",
    fetcherType: "betterstack",
  },
  {
    id: "yugabyte",
    name: "Yugabyte",
    category: "data",
    statusUrl: "https://status.yugabyte.cloud/",
    fetcherType: "statuspage",
  },
  {
    id: "tidb",
    name: "TiDB",
    category: "data",
    statusUrl: "https://status.tidbcloud.com/",
    fetcherType: "statuspage",
  },
  {
    id: "datastax",
    name: "DataStax",
    category: "data",
    statusUrl: "https://status.datastax.com/",
    fetcherType: "none",
  },
  {
    id: "auth0",
    name: "Auth0",
    category: "auth",
    statusUrl: "https://status.auth0.com/",
    fetcherType: "statuspage",
  },
  {
    id: "clerk",
    name: "Clerk",
    category: "auth",
    statusUrl: "https://status.clerk.com/",
    fetcherType: "statuspage",
  },
  {
    id: "workos",
    name: "WorkOS",
    category: "auth",
    statusUrl: "https://status.workos.com/",
    fetcherType: "statuspage",
  },
  {
    id: "okta",
    name: "Okta",
    category: "auth",
    statusUrl: "https://status.okta.com/",
    fetcherType: "none",
  },
  {
    id: "stytch",
    name: "Stytch",
    category: "auth",
    statusUrl: "https://status.stytch.com/",
    fetcherType: "instatus",
  },
  {
    id: "kinde",
    name: "Kinde",
    category: "auth",
    statusUrl: "https://status.kinde.com/",
    fetcherType: "instatus",
  },
  {
    id: "fusionauth",
    name: "FusionAuth",
    category: "auth",
    statusUrl: "https://status.fusionauth.io/",
    fetcherType: "statuspage",
  },
  {
    id: "frontegg",
    name: "Frontegg",
    category: "auth",
    statusUrl: "https://status.frontegg.com/",
    fetcherType: "statuspage",
  },
  {
    id: "propelauth",
    name: "PropelAuth",
    category: "auth",
    statusUrl: "https://status.propelauth.com/",
    fetcherType: "instatus",
  },
  {
    id: "onepassword",
    name: "1Password",
    category: "auth",
    statusUrl: "https://status.1password.com/",
    fetcherType: "statuspage",
  },
  {
    id: "descope",
    name: "Descope",
    category: "auth",
    statusUrl: "https://descopestatus.com/",
    fetcherType: "instatus",
  },
  {
    id: "duo",
    name: "Duo",
    category: "auth",
    statusUrl: "https://status.duo.com/",
    fetcherType: "statuspage",
  },
  {
    id: "ping-identity",
    name: "Ping Identity",
    category: "auth",
    statusUrl: "https://status.pingidentity.com/",
    fetcherType: "statuspage",
  },
  {
    id: "doppler",
    name: "Doppler",
    category: "auth",
    statusUrl: "https://www.dopplerstatus.com/",
    fetcherType: "statuspage",
  },
  {
    id: "infisical",
    name: "Infisical",
    category: "auth",
    statusUrl: "https://status.infisical.com/",
    fetcherType: "statuspage",
  },
  {
    id: "zitadel",
    name: "Zitadel",
    category: "auth",
    statusUrl: "https://www.zitadelstatus.com/",
    fetcherType: "statuspage",
  },
  {
    id: "jumpcloud",
    name: "JumpCloud",
    category: "auth",
    statusUrl: "https://status.jumpcloud.com/",
    fetcherType: "statuspage",
  },
  {
    id: "logto",
    name: "Logto",
    category: "auth",
    statusUrl: "https://status.logto.io/",
    fetcherType: "betterstack",
  },
  {
    id: "magic",
    name: "Magic",
    category: "auth",
    statusUrl: "https://status.magic.link/",
    fetcherType: "statuspage",
  },
  {
    id: "beyond-identity",
    name: "Beyond Identity",
    category: "auth",
    statusUrl: "https://status.beyondidentity.com/",
    fetcherType: "statuspage",
  },
  {
    id: "loginradius",
    name: "LoginRadius",
    category: "auth",
    statusUrl: "https://status.loginradius.com/",
    fetcherType: "statuspage",
  },
  {
    id: "scalekit",
    name: "Scalekit",
    category: "auth",
    statusUrl: "https://scalekit.statuspage.io/",
    fetcherType: "statuspage",
  },
  {
    id: "transmit-security",
    name: "Transmit Security",
    category: "auth",
    statusUrl: "https://status.transmitsecurity.io/",
    fetcherType: "statuspage",
  },
  {
    id: "secureauth",
    name: "SecureAuth",
    category: "auth",
    statusUrl: "https://status.secureauth.com/",
    fetcherType: "statuspage",
  },
  {
    id: "lastpass",
    name: "LastPass",
    category: "auth",
    statusUrl: "https://status.lastpass.com/",
    fetcherType: "statuspage",
  },
  {
    id: "keeper",
    name: "Keeper",
    category: "auth",
    statusUrl: "https://statuspage.keeper.io/",
    fetcherType: "statuspage",
  },
  {
    id: "yubico",
    name: "Yubico",
    category: "auth",
    statusUrl: "https://status.yubico.com/",
    fetcherType: "statuspage",
  },
  {
    id: "akeyless",
    name: "Akeyless",
    category: "auth",
    statusUrl: "https://status.akeyless.io/",
    fetcherType: "statuspage",
  },
  {
    id: "sailpoint",
    name: "SailPoint",
    category: "auth",
    statusUrl: "https://status.sailpoint.com/",
    fetcherType: "statuspage",
  },
  {
    id: "delinea",
    name: "Delinea",
    category: "auth",
    statusUrl: "https://status.delinea.com/",
    fetcherType: "statuspage",
  },
  {
    id: "stripe",
    name: "Stripe",
    category: "payments",
    statusUrl: "https://status.stripe.com/",
    fetcherType: "statuspage",
  },
  {
    id: "paypal",
    name: "PayPal",
    category: "payments",
    statusUrl: "https://www.paypal-status.com/",
    fetcherType: "none",
  },
  {
    id: "square",
    name: "Square",
    category: "payments",
    statusUrl: "https://www.issquareup.com/",
    fetcherType: "statuspage",
  },
  {
    id: "adyen",
    name: "Adyen",
    category: "payments",
    statusUrl: "https://status.adyen.com/",
    fetcherType: "none",
  },
  {
    id: "paddle",
    name: "Paddle",
    category: "payments",
    statusUrl: "https://paddlestatus.com/",
    fetcherType: "statuspage",
  },
  {
    id: "chargebee",
    name: "Chargebee",
    category: "payments",
    statusUrl: "https://status.chargebee.com/",
    fetcherType: "statuspage",
  },
  {
    id: "recurly",
    name: "Recurly",
    category: "payments",
    statusUrl: "https://status.recurly.com/",
    fetcherType: "statuspage",
  },
  {
    id: "klarna",
    name: "Klarna",
    category: "payments",
    statusUrl: "https://status.klarna.com/",
    fetcherType: "statuspage",
  },
  {
    id: "plaid",
    name: "Plaid",
    category: "payments",
    statusUrl: "https://status.plaid.com/",
    fetcherType: "statuspage",
  },
  {
    id: "gocardless",
    name: "GoCardless",
    category: "payments",
    statusUrl: "https://www.gocardless-status.com/",
    fetcherType: "statuspage",
  },
  {
    id: "mollie",
    name: "Mollie",
    category: "payments",
    statusUrl: "https://status.mollie.com/",
    fetcherType: "instatus",
  },
  {
    id: "polar",
    name: "Polar",
    category: "payments",
    statusUrl: "https://status.polar.sh/",
    fetcherType: "betterstack",
  },
  {
    id: "revenuecat",
    name: "RevenueCat",
    category: "payments",
    statusUrl: "https://status.revenuecat.com/",
    fetcherType: "statuspage",
  },
  {
    id: "affirm",
    name: "Affirm",
    category: "payments",
    statusUrl: "https://status.affirm.com/",
    fetcherType: "statuspage",
  },
  {
    id: "fastspring",
    name: "FastSpring",
    category: "payments",
    statusUrl: "https://status.fastspring.com/",
    fetcherType: "statuspage",
  },
  {
    id: "whop",
    name: "Whop",
    category: "payments",
    statusUrl: "https://status.whop.com/",
    fetcherType: "statuspage",
  },
  {
    id: "wise",
    name: "Wise",
    category: "payments",
    statusUrl: "https://status.wise.com/",
    fetcherType: "statuspage",
  },
  {
    id: "authorize-net",
    name: "Authorize.net",
    category: "payments",
    statusUrl: "https://status.authorize.net/",
    fetcherType: "statuspage",
  },
  {
    id: "flutterwave",
    name: "Flutterwave",
    category: "payments",
    statusUrl: "https://status.flutterwave.com/",
    fetcherType: "statuspage",
  },
  {
    id: "airwallex",
    name: "Airwallex",
    category: "payments",
    statusUrl: "https://status.airwallex.com/",
    fetcherType: "statuspage",
  },
  {
    id: "marqeta",
    name: "Marqeta",
    category: "payments",
    statusUrl: "https://status.marqeta.com/",
    fetcherType: "statuspage",
  },
  {
    id: "lithic",
    name: "Lithic",
    category: "payments",
    statusUrl: "https://status.lithic.com/",
    fetcherType: "statuspage",
  },
  {
    id: "worldpay",
    name: "Worldpay",
    category: "payments",
    statusUrl: "https://status.worldpay.com/",
    fetcherType: "statuspage",
  },
  {
    id: "spreedly",
    name: "Spreedly",
    category: "payments",
    statusUrl: "https://status.spreedly.com/",
    fetcherType: "statuspage",
  },
  {
    id: "finix",
    name: "Finix",
    category: "payments",
    statusUrl: "https://status.finix.com/",
    fetcherType: "statuspage",
  },
  {
    id: "mercado-pago",
    name: "Mercado Pago",
    category: "payments",
    statusUrl: "https://status.mercadopago.com/",
    fetcherType: "statuspage",
  },
  {
    id: "ebanx",
    name: "EBANX",
    category: "payments",
    statusUrl: "https://status.ebanx.com/",
    fetcherType: "statuspage",
  },
  {
    id: "paysafe",
    name: "Paysafe",
    category: "payments",
    statusUrl: "https://status.paysafe.com/",
    fetcherType: "statuspage",
  },
  {
    id: "recharge",
    name: "Recharge",
    category: "payments",
    statusUrl: "https://status.getrecharge.com/",
    fetcherType: "statuspage",
  },
  {
    id: "maxio",
    name: "Maxio",
    category: "payments",
    statusUrl: "https://maxio.statuspage.io/",
    fetcherType: "statuspage",
  },
  {
    id: "datadog",
    name: "Datadog",
    category: "observability",
    statusUrl: "https://status.datadoghq.com/",
    fetcherType: "statuspage",
  },
  {
    id: "sentry",
    name: "Sentry",
    category: "observability",
    statusUrl: "https://status.sentry.io/",
    fetcherType: "statuspage",
  },
  {
    id: "grafana",
    name: "Grafana",
    category: "observability",
    statusUrl: "https://status.grafana.com/",
    fetcherType: "statuspage",
  },
  {
    id: "pagerduty",
    name: "PagerDuty",
    category: "observability",
    statusUrl: "https://status.pagerduty.com/",
    fetcherType: "none",
  },
  {
    id: "new-relic",
    name: "New Relic",
    category: "observability",
    statusUrl: "https://status.newrelic.com/",
    fetcherType: "statuspage",
  },
  {
    id: "honeycomb",
    name: "Honeycomb",
    category: "observability",
    statusUrl: "https://status.honeycomb.io/",
    fetcherType: "statuspage",
  },
  {
    id: "splunk",
    name: "Splunk",
    category: "observability",
    statusUrl: "https://status.splunkcloud.com/",
    fetcherType: "statuspage",
  },
  {
    id: "dynatrace",
    name: "Dynatrace",
    category: "observability",
    statusUrl: "https://status.dynatrace.com/",
    fetcherType: "status_io",
  },
  {
    id: "better-stack",
    name: "Better Stack",
    category: "observability",
    statusUrl: "https://status.betterstack.com/",
    fetcherType: "betterstack",
  },
  {
    id: "axiom",
    name: "Axiom",
    category: "observability",
    statusUrl: "https://status.axiom.co/",
    fetcherType: "statuspage",
  },
  {
    id: "sumo-logic",
    name: "Sumo Logic",
    category: "observability",
    statusUrl: "https://status.sumologic.com/",
    fetcherType: "statuspage",
  },
  {
    id: "coralogix",
    name: "Coralogix",
    category: "observability",
    statusUrl: "https://status.coralogix.com/",
    fetcherType: "statuspage",
  },
  {
    id: "rollbar",
    name: "Rollbar",
    category: "observability",
    statusUrl: "https://status.rollbar.com/",
    fetcherType: "statuspage",
  },
  {
    id: "bugsnag",
    name: "Bugsnag",
    category: "observability",
    statusUrl: "https://status.bugsnag.com/",
    fetcherType: "statuspage",
  },
  {
    id: "incident-io",
    name: "incident.io",
    category: "observability",
    statusUrl: "https://status.incident.io/",
    fetcherType: "statuspage",
  },
  {
    id: "mezmo",
    name: "Mezmo",
    category: "observability",
    statusUrl: "https://status.mezmo.com/",
    fetcherType: "statuspage",
  },
  {
    id: "airbrake",
    name: "Airbrake",
    category: "observability",
    statusUrl: "https://status.airbrake.io/",
    fetcherType: "statuspage",
  },
  {
    id: "checkly",
    name: "Checkly",
    category: "observability",
    statusUrl: "https://status.checklyhq.com/",
    fetcherType: "none",
  },
  {
    id: "cribl",
    name: "Cribl",
    category: "observability",
    statusUrl: "https://status.cribl.cloud/",
    fetcherType: "statuspage",
  },
  {
    id: "logz",
    name: "logz.io",
    category: "observability",
    statusUrl: "https://status.logz.io/",
    fetcherType: "statuspage",
  },
  {
    id: "lumigo",
    name: "Lumigo",
    category: "observability",
    statusUrl: "https://status.lumigo.io/",
    fetcherType: "statuspage",
  },
  {
    id: "netdata",
    name: "Netdata",
    category: "observability",
    statusUrl: "https://status.netdata.cloud/",
    fetcherType: "statuspage",
  },
  {
    id: "scout",
    name: "Scout",
    category: "observability",
    statusUrl: "https://status.scoutapm.com/",
    fetcherType: "statuspage",
  },
  {
    id: "logit",
    name: "Logit.io",
    category: "observability",
    statusUrl: "https://status.logit.io/",
    fetcherType: "statuspage",
  },
  {
    id: "nobl9",
    name: "Nobl9",
    category: "observability",
    statusUrl: "https://status.nobl9.com/",
    fetcherType: "statuspage",
  },
  {
    id: "catchpoint",
    name: "Catchpoint",
    category: "observability",
    statusUrl: "https://status.catchpoint.com/",
    fetcherType: "statuspage",
  },
  {
    id: "victoria-metrics",
    name: "VictoriaMetrics",
    category: "observability",
    statusUrl: "https://status.victoriametrics.com/",
    fetcherType: "statuspage",
  },
  {
    id: "langfuse",
    name: "Langfuse",
    category: "observability",
    statusUrl: "https://status.langfuse.com/",
    fetcherType: "statuspage",
  },
  {
    id: "dash0",
    name: "Dash0",
    category: "observability",
    statusUrl: "https://status.dash0.com/",
    fetcherType: "statuspage",
  },
  {
    id: "embrace",
    name: "Embrace",
    category: "observability",
    statusUrl: "https://status.embrace.io/",
    fetcherType: "statuspage",
  },
  {
    id: "twilio",
    name: "Twilio",
    category: "email",
    statusUrl: "https://status.twilio.com/",
    fetcherType: "statuspage",
  },
  {
    id: "mailgun",
    name: "Mailgun",
    category: "email",
    statusUrl: "https://status.mailgun.com/",
    fetcherType: "statuspage",
  },
  {
    id: "resend",
    name: "Resend",
    category: "email",
    statusUrl: "https://status.resend.com/",
    fetcherType: "statuspage",
  },
  {
    id: "klaviyo",
    name: "Klaviyo",
    category: "email",
    statusUrl: "https://status.klaviyo.com/",
    fetcherType: "statuspage",
  },
  {
    id: "brevo",
    name: "Brevo",
    category: "email",
    statusUrl: "https://status.brevo.com/",
    fetcherType: "statuspage",
  },
  {
    id: "customer-io",
    name: "Customer.io",
    category: "email",
    statusUrl: "https://status.customer.io/",
    fetcherType: "statuspage",
  },
  {
    id: "sparkpost",
    name: "SparkPost",
    category: "email",
    statusUrl: "https://status.sparkpost.com/",
    fetcherType: "statuspage",
  },
  {
    id: "braze",
    name: "Braze",
    category: "email",
    statusUrl: "https://status.braze.com/",
    fetcherType: "statuspage",
  },
  {
    id: "loops",
    name: "Loops",
    category: "email",
    statusUrl: "https://status.loops.so/",
    fetcherType: "statuspage",
  },
  {
    id: "mailjet",
    name: "Mailjet",
    category: "email",
    statusUrl: "https://status.mailjet.com/",
    fetcherType: "statuspage",
  },
  {
    id: "knock",
    name: "Knock",
    category: "email",
    statusUrl: "https://status.knock.app/",
    fetcherType: "statuspage",
  },
  {
    id: "iterable",
    name: "Iterable",
    category: "email",
    statusUrl: "https://status.iterable.com/",
    fetcherType: "statuspage",
  },
  {
    id: "mailersend",
    name: "MailerSend",
    category: "email",
    statusUrl: "https://status.mailersend.com/",
    fetcherType: "statuspage",
  },
  {
    id: "mailerlite",
    name: "MailerLite",
    category: "email",
    statusUrl: "https://status.mailerlite.com/",
    fetcherType: "statuspage",
  },
  {
    id: "smtp2go",
    name: "SMTP2GO",
    category: "email",
    statusUrl: "https://status.smtp2go.com/",
    fetcherType: "statuspage",
  },
  {
    id: "kit",
    name: "Kit",
    category: "email",
    statusUrl: "https://status.kit.com/",
    fetcherType: "statuspage",
  },
  {
    id: "front",
    name: "Front",
    category: "email",
    statusUrl: "https://www.frontstatus.com/",
    fetcherType: "statuspage",
  },
  {
    id: "omnisend",
    name: "Omnisend",
    category: "email",
    statusUrl: "https://status.omnisend.com/",
    fetcherType: "statuspage",
  },
  {
    id: "postmark",
    name: "Postmark",
    category: "email",
    statusUrl: "https://status.postmarkapp.com/",
    fetcherType: "none",
  },
  {
    id: "mailchimp",
    name: "Mailchimp",
    category: "email",
    statusUrl: "https://status.mailchimp.com/",
    fetcherType: "none",
  },
  {
    id: "activecampaign",
    name: "ActiveCampaign",
    category: "email",
    statusUrl: "https://status.activecampaign.com/",
    fetcherType: "statuspage",
  },
  {
    id: "getresponse",
    name: "GetResponse",
    category: "email",
    statusUrl: "https://status.getresponse.com/",
    fetcherType: "statuspage",
  },
  {
    id: "campaign-monitor",
    name: "Campaign Monitor",
    category: "email",
    statusUrl: "https://status.campaignmonitor.com/",
    fetcherType: "none",
  },
  {
    id: "nylas",
    name: "Nylas",
    category: "email",
    statusUrl: "https://status.nylas.com/",
    fetcherType: "statuspage",
  },
  {
    id: "emailoctopus",
    name: "EmailOctopus",
    category: "email",
    statusUrl: "https://status.emailoctopus.com/",
    fetcherType: "statuspage",
  },
  {
    id: "onesignal",
    name: "OneSignal",
    category: "email",
    statusUrl: "https://status.onesignal.com/",
    fetcherType: "statuspage",
  },
  {
    id: "hubspot",
    name: "HubSpot",
    category: "email",
    statusUrl: "https://status.hubspot.com/",
    fetcherType: "statuspage",
  },
  {
    id: "help-scout",
    name: "Help Scout",
    category: "email",
    statusUrl: "https://status.helpscout.com/",
    fetcherType: "statuspage",
  },
  {
    id: "mailtrap",
    name: "Mailtrap",
    category: "email",
    statusUrl: "https://status.mailtrap.info/",
    fetcherType: "none",
  },
  {
    id: "substack",
    name: "Substack",
    category: "email",
    statusUrl: "https://status.substack.com/",
    fetcherType: "none",
  },
  // Design Wave A. FigJam / Dev Mode stay on Figma. Photoshop /
  // Illustrator / XD stay on Adobe. Lucidspark stays on Lucid. Spline
  // waits (no official vector). Adobe and Sketch are none.
  {
    id: "figma",
    name: "Figma",
    category: "design",
    statusUrl: "https://status.figma.com/",
    fetcherType: "statuspage",
  },
  {
    id: "canva",
    name: "Canva",
    category: "design",
    statusUrl: "https://www.canvastatus.com/",
    fetcherType: "statuspage",
  },
  {
    id: "adobe",
    name: "Adobe",
    category: "design",
    statusUrl: "https://status.adobe.com/",
    fetcherType: "none",
  },
  {
    id: "sketch",
    name: "Sketch",
    category: "design",
    statusUrl: "https://status.sketch.com/",
    fetcherType: "none",
  },
  {
    id: "framer",
    name: "Framer",
    category: "design",
    statusUrl: "https://www.framerstatus.com/",
    fetcherType: "betterstack",
  },
  {
    id: "miro",
    name: "Miro",
    category: "design",
    statusUrl: "https://status.miro.com/",
    fetcherType: "statuspage",
  },
  {
    id: "webflow",
    name: "Webflow",
    category: "design",
    statusUrl: "https://status.webflow.com/",
    fetcherType: "statuspage",
  },
  {
    id: "lucid",
    name: "Lucid",
    category: "design",
    statusUrl: "https://status.lucid.co/",
    fetcherType: "statuspage",
  },
  {
    id: "mural",
    name: "Mural",
    category: "design",
    statusUrl: "https://status.mural.co/",
    fetcherType: "statuspage",
  },
  {
    id: "frontify",
    name: "Frontify",
    category: "design",
    statusUrl: "https://status.frontify.com/",
    fetcherType: "statuspage",
  },
  // Design Wave B. Affinity stays on Canva. Abstract / InVision stay
  // off (sunset). Spline still waits. Marvel, Balsamiq, and Anima are
  // Statuspage; the rest are none (custom pages or no public JSON).
  {
    id: "penpot",
    name: "Penpot",
    category: "design",
    statusUrl: "https://penpot.app/",
    fetcherType: "none",
  },
  {
    id: "marvel",
    name: "Marvel",
    category: "design",
    statusUrl: "https://status.marvelapp.com/",
    fetcherType: "statuspage",
  },
  {
    id: "rive",
    name: "Rive",
    category: "design",
    statusUrl: "https://status.rive.app/",
    fetcherType: "none",
  },
  {
    id: "lottiefiles",
    name: "LottieFiles",
    category: "design",
    statusUrl: "https://status.lottiefiles.com/",
    fetcherType: "none",
  },
  {
    id: "balsamiq",
    name: "Balsamiq",
    category: "design",
    statusUrl: "https://status.balsamiq.com/",
    fetcherType: "statuspage",
  },
  {
    id: "anima",
    name: "Anima",
    category: "design",
    statusUrl: "https://status.animaapp.com/",
    fetcherType: "statuspage",
  },
  {
    id: "whimsical",
    name: "Whimsical",
    category: "design",
    statusUrl: "https://status.whimsical.com/",
    fetcherType: "none",
  },
  {
    id: "lunacy",
    name: "Lunacy",
    category: "design",
    statusUrl: "https://icons8.com/lunacy",
    fetcherType: "none",
  },
  {
    id: "photopea",
    name: "Photopea",
    category: "design",
    statusUrl: "https://www.photopea.com/",
    fetcherType: "none",
  },
  {
    id: "blender",
    name: "Blender",
    category: "design",
    statusUrl: "https://status.blender.org/",
    fetcherType: "none",
  },
  // Design Wave C. Spline still waits. Zeplin / ProtoPie / Builder.io
  // wait. Beautiful.ai and Jitter are Statuspage; the rest are none.
  {
    id: "moqups",
    name: "Moqups",
    category: "design",
    statusUrl: "https://moqups.com/",
    fetcherType: "none",
  },
  {
    id: "proto-io",
    name: "Proto.io",
    category: "design",
    statusUrl: "https://proto.io/",
    fetcherType: "none",
  },
  {
    id: "uxpin",
    name: "UXPin",
    category: "design",
    statusUrl: "https://www.uxpin.com/",
    fetcherType: "none",
  },
  {
    id: "overflow",
    name: "Overflow",
    category: "design",
    statusUrl: "https://overflow.io/",
    fetcherType: "none",
  },
  {
    id: "axure",
    name: "Axure",
    category: "design",
    statusUrl: "https://www.axure.com/",
    fetcherType: "none",
  },
  {
    id: "relume",
    name: "Relume",
    category: "design",
    statusUrl: "https://www.relume.io/",
    fetcherType: "none",
  },
  {
    id: "visily",
    name: "Visily",
    category: "design",
    statusUrl: "https://www.visily.ai/",
    fetcherType: "none",
  },
  {
    id: "plasmic",
    name: "Plasmic",
    category: "design",
    statusUrl: "https://www.plasmic.app/",
    fetcherType: "none",
  },
  {
    id: "beautiful-ai",
    name: "Beautiful.ai",
    category: "design",
    statusUrl: "https://status.beautiful.ai/",
    fetcherType: "statuspage",
  },
  {
    id: "jitter",
    name: "Jitter",
    category: "design",
    statusUrl: "https://jitter.statuspage.io/",
    fetcherType: "statuspage",
  },
  // Infra Wave A. HashiCorp products share status.hashicorp.com
  // (HCP rollup). Spacelift's public host has no DNS; hit
  // spacelift.statuspage.io. Crossplane polls Upbound's Statuspage.
  // OpenTofu is HTML-only (no public JSON).
  {
    id: "terraform",
    name: "Terraform",
    category: "infra",
    statusUrl: "https://status.hashicorp.com/",
    fetcherType: "statuspage",
  },
  {
    id: "pulumi",
    name: "Pulumi",
    category: "infra",
    statusUrl: "https://status.pulumi.com/",
    fetcherType: "statuspage",
  },
  {
    id: "vault",
    name: "Vault",
    category: "infra",
    statusUrl: "https://status.hashicorp.com/",
    fetcherType: "statuspage",
  },
  {
    id: "consul",
    name: "Consul",
    category: "infra",
    statusUrl: "https://status.hashicorp.com/",
    fetcherType: "statuspage",
  },
  {
    id: "nomad",
    name: "Nomad",
    category: "infra",
    statusUrl: "https://status.hashicorp.com/",
    fetcherType: "statuspage",
  },
  {
    id: "spacelift",
    name: "Spacelift",
    category: "infra",
    statusUrl: "https://spacelift.statuspage.io/",
    fetcherType: "statuspage",
  },
  {
    id: "crossplane",
    name: "Crossplane",
    category: "infra",
    statusUrl: "https://status.upbound.io/",
    fetcherType: "statuspage",
  },
  {
    id: "packer",
    name: "Packer",
    category: "infra",
    statusUrl: "https://status.hashicorp.com/",
    fetcherType: "statuspage",
  },
  {
    id: "chef",
    name: "Chef",
    category: "infra",
    statusUrl: "https://status.chef.io/",
    fetcherType: "statuspage",
  },
  {
    id: "opentofu",
    name: "OpenTofu",
    category: "infra",
    statusUrl: "https://status.opentofu.org/",
    fetcherType: "none",
  },
  // Infra Wave B. Puppet's public host has no DNS; hit
  // puppet.statuspage.io. Scalr is Statuspage. Ansible / Argo CD /
  // Flux / Terragrunt / Env0 / Salt / Rancher / Vagrant are none.
  {
    id: "ansible",
    name: "Ansible",
    category: "infra",
    statusUrl: "https://www.ansible.com/",
    fetcherType: "none",
  },
  {
    id: "puppet",
    name: "Puppet",
    category: "infra",
    statusUrl: "https://puppet.statuspage.io/",
    fetcherType: "statuspage",
  },
  {
    id: "argo-cd",
    name: "Argo CD",
    category: "infra",
    statusUrl: "https://argo-cd.readthedocs.io/en/stable/",
    fetcherType: "none",
  },
  {
    id: "flux",
    name: "Flux",
    category: "infra",
    statusUrl: "https://fluxcd.io/",
    fetcherType: "none",
  },
  {
    id: "terragrunt",
    name: "Terragrunt",
    category: "infra",
    statusUrl: "https://terragrunt.gruntwork.io/",
    fetcherType: "none",
  },
  {
    id: "env0",
    name: "Env0",
    category: "infra",
    statusUrl: "https://status.env0.com/",
    fetcherType: "none",
  },
  {
    id: "scalr",
    name: "Scalr",
    category: "infra",
    statusUrl: "https://status.scalr.io/",
    fetcherType: "statuspage",
  },
  {
    id: "salt",
    name: "Salt",
    category: "infra",
    statusUrl: "https://saltproject.io/",
    fetcherType: "none",
  },
  {
    id: "rancher",
    name: "Rancher",
    category: "infra",
    statusUrl: "https://www.rancher.com/",
    fetcherType: "none",
  },
  {
    id: "vagrant",
    name: "Vagrant",
    category: "infra",
    statusUrl: "https://www.vagrantup.com/",
    fetcherType: "none",
  },
  // Infra Wave C. Teleport is Statuspage. Helm / Istio / Linkerd /
  // Cilium / OPA / Kyverno / Traefik / cert-manager / Infracost
  // are none (project sites, no public JSON).
  {
    id: "helm",
    name: "Helm",
    category: "infra",
    statusUrl: "https://helm.sh/",
    fetcherType: "none",
  },
  {
    id: "teleport",
    name: "Teleport",
    category: "infra",
    statusUrl: "https://status.goteleport.com/",
    fetcherType: "statuspage",
  },
  {
    id: "istio",
    name: "Istio",
    category: "infra",
    statusUrl: "https://istio.io/",
    fetcherType: "none",
  },
  {
    id: "linkerd",
    name: "Linkerd",
    category: "infra",
    statusUrl: "https://linkerd.io/",
    fetcherType: "none",
  },
  {
    id: "cilium",
    name: "Cilium",
    category: "infra",
    statusUrl: "https://cilium.io/",
    fetcherType: "none",
  },
  {
    id: "opa",
    name: "OPA",
    category: "infra",
    statusUrl: "https://www.openpolicyagent.org/",
    fetcherType: "none",
  },
  {
    id: "kyverno",
    name: "Kyverno",
    category: "infra",
    statusUrl: "https://kyverno.io/",
    fetcherType: "none",
  },
  {
    id: "traefik",
    name: "Traefik",
    category: "infra",
    statusUrl: "https://traefik.io/",
    fetcherType: "none",
  },
  {
    id: "cert-manager",
    name: "cert-manager",
    category: "infra",
    statusUrl: "https://cert-manager.io/",
    fetcherType: "none",
  },
  {
    id: "infracost",
    name: "Infracost",
    category: "infra",
    statusUrl: "https://www.infracost.io/",
    fetcherType: "none",
  },
  // Flags Wave A. LaunchDarkly / Optimizely / Statsig / Flagsmith
  // are Statuspage. DevCycle is Status.io. Unleash / ConfigCat /
  // GrowthBook / Eppo / VWO are none (no public JSON).
  {
    id: "launchdarkly",
    name: "LaunchDarkly",
    category: "flags",
    statusUrl: "https://status.launchdarkly.com/",
    fetcherType: "statuspage",
  },
  {
    id: "optimizely",
    name: "Optimizely",
    category: "flags",
    statusUrl: "https://status.optimizely.com/",
    fetcherType: "statuspage",
  },
  {
    id: "statsig",
    name: "Statsig",
    category: "flags",
    statusUrl: "https://status.statsig.com/",
    fetcherType: "statuspage",
  },
  {
    id: "flagsmith",
    name: "Flagsmith",
    category: "flags",
    statusUrl: "https://status.flagsmith.com/",
    fetcherType: "statuspage",
  },
  {
    id: "unleash",
    name: "Unleash",
    category: "flags",
    statusUrl: "https://www.getunleash.io/",
    fetcherType: "none",
  },
  {
    id: "configcat",
    name: "ConfigCat",
    category: "flags",
    statusUrl: "https://status.configcat.com/",
    fetcherType: "none",
  },
  {
    id: "growthbook",
    name: "GrowthBook",
    category: "flags",
    statusUrl: "https://www.growthbook.io/",
    fetcherType: "none",
  },
  {
    id: "devcycle",
    name: "DevCycle",
    category: "flags",
    statusUrl: "https://status.devcycle.com/",
    fetcherType: "status_io",
  },
  {
    id: "eppo",
    name: "Eppo",
    category: "flags",
    statusUrl: "https://www.geteppo.com/",
    fetcherType: "none",
  },
  {
    id: "vwo",
    name: "VWO",
    category: "flags",
    statusUrl: "https://status.vwo.com/",
    fetcherType: "none",
  },
  // Flags Wave B. CloudBees / Kameleoon / Monetate are Statuspage
  // (Kameleoon and Monetate public hosts have no DNS). Reflag is
  // Instatus. AB Tasty / Convert / Flipt / Hypertune / GO Feature
  // Flag / FeatBit are none (no public JSON; convert.statuspage.io
  // is an unrelated example page).
  {
    id: "cloudbees",
    name: "CloudBees",
    category: "flags",
    statusUrl: "https://www.cloudbeesstatus.com/",
    fetcherType: "statuspage",
  },
  {
    id: "ab-tasty",
    name: "AB Tasty",
    category: "flags",
    statusUrl: "https://status.abtasty.com/",
    fetcherType: "none",
  },
  {
    id: "kameleoon",
    name: "Kameleoon",
    category: "flags",
    statusUrl: "https://kameleoon.statuspage.io/",
    fetcherType: "statuspage",
  },
  {
    id: "convert",
    name: "Convert",
    category: "flags",
    statusUrl: "https://status.convert.com/",
    fetcherType: "none",
  },
  {
    id: "monetate",
    name: "Monetate",
    category: "flags",
    statusUrl: "https://monetate.statuspage.io/",
    fetcherType: "statuspage",
  },
  {
    id: "flipt",
    name: "Flipt",
    category: "flags",
    statusUrl: "https://www.flipt.io/",
    fetcherType: "none",
  },
  {
    id: "hypertune",
    name: "Hypertune",
    category: "flags",
    statusUrl: "https://www.hypertune.com/",
    fetcherType: "none",
  },
  {
    id: "reflag",
    name: "Reflag",
    category: "flags",
    statusUrl: "https://status.reflag.com/",
    fetcherType: "instatus",
  },
  {
    id: "go-feature-flag",
    name: "GO Feature Flag",
    category: "flags",
    statusUrl: "https://gofeatureflag.org/",
    fetcherType: "none",
  },
  {
    id: "featbit",
    name: "FeatBit",
    category: "flags",
    statusUrl: "https://www.featbit.co/",
    fetcherType: "none",
  },
] as const

function seedCategory(service: { id: string }): string {
  return "category" in service && typeof service.category === "string"
    ? service.category
    : "ai"
}

export async function seedServices(pool: pg.Pool): Promise<void> {
  for (const service of SERVICE_SEED) {
    await pool.query(
      `INSERT INTO services (id, name, category, status_url, fetcher_type)
       VALUES ($1, $2, $3, $4, $5)
       ON CONFLICT (id) DO UPDATE
         SET name = EXCLUDED.name,
             category = EXCLUDED.category,
             status_url = EXCLUDED.status_url,
             fetcher_type = EXCLUDED.fetcher_type,
             updated_at = now()`,
      [
        service.id,
        service.name,
        seedCategory(service),
        service.statusUrl,
        "fetcherType" in service ? service.fetcherType : "none",
      ],
    )
  }
}
