import type pg from "pg"

/**
 * Static registry of board services (26 AI + Cloud Waves A–C + Developer Waves A–C + Data Waves A–C).
 * Mirrors the ids in the Next.js app's data/services.ts (and public/logos/{id}.svg).
 * Windsurf is the legacy Devin Desktop name and is not seeded separately.
 * GitHub Copilot is a GitHub component, not its own card.
 *
 * `category` defaults to `ai` when omitted. AWS, Azure, Fastly, Replit,
 * Redis, Algolia, and DataStax are `none` until a dedicated fetcher exists.
 */
export const SERVICE_SEED = [
  {
    id: "openai",
    name: "OpenAI",
    statusUrl: "https://status.openai.com/",
    fetcherType: "statuspage",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    statusUrl: "https://status.claude.com/",
    fetcherType: "statuspage",
  },
  {
    id: "google-gemini",
    name: "Google Gemini",
    statusUrl: "https://aistudio.google.com/status",
    fetcherType: "google_cloud",
  },
  { id: "xai", name: "xAI", statusUrl: "https://status.x.ai/", fetcherType: "rss" },
  {
    id: "mistral",
    name: "Mistral",
    statusUrl: "https://status.mistral.ai/",
    fetcherType: "checkly_nuxt",
  },
  { id: "groq", name: "Groq", statusUrl: "https://groqstatus.com/", fetcherType: "statuspage" },
  {
    id: "perplexity",
    name: "Perplexity",
    statusUrl: "https://status.perplexity.com/",
    fetcherType: "instatus",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    statusUrl: "https://status.deepseek.com/",
    fetcherType: "rss",
  },
  {
    id: "cohere",
    name: "Cohere",
    statusUrl: "https://status.cohere.com/",
    fetcherType: "statuspage",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    statusUrl: "https://status.openrouter.ai/",
    fetcherType: "onlineornot",
  },
  {
    id: "fireworks",
    name: "Fireworks AI",
    statusUrl: "https://status.fireworks.ai/",
    fetcherType: "statuspage",
  },
  {
    id: "together",
    name: "Together AI",
    statusUrl: "https://status.together.ai/",
    fetcherType: "betterstack",
  },
  {
    id: "cerebras",
    name: "Cerebras",
    statusUrl: "https://status.cerebras.ai/",
    fetcherType: "statuspage",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    statusUrl: "https://status.huggingface.co/",
    fetcherType: "betterstack",
  },
  {
    id: "replicate",
    name: "Replicate",
    statusUrl: "https://status.replicate.com/",
    fetcherType: "statuspage",
  },
  {
    id: "runway",
    name: "Runway",
    statusUrl: "https://status.runwayml.com/",
    fetcherType: "statuspage",
  },
  {
    id: "ideogram",
    name: "Ideogram",
    statusUrl: "https://status.ideogram.ai/",
    fetcherType: "statuspage",
  },
  {
    id: "stability",
    name: "Stability AI",
    statusUrl: "https://status.stability.ai/",
    fetcherType: "statuspage",
  },
  {
    id: "fal",
    name: "fal",
    statusUrl: "https://status.fal.ai/",
    fetcherType: "instatus",
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    statusUrl: "https://status.elevenlabs.io/",
    fetcherType: "statuspage",
  },
  {
    id: "minimax",
    name: "MiniMax",
    statusUrl: "https://status.minimax.io/",
    fetcherType: "statuspage",
  },
  {
    id: "voyage",
    name: "Voyage AI",
    statusUrl: "https://status.voyageai.com/",
    fetcherType: "statuspage",
  },
  {
    id: "bfl",
    name: "Black Forest Labs",
    statusUrl: "https://status.bfl.ml/",
    fetcherType: "statuspage",
  },
  {
    id: "cartesia",
    name: "Cartesia",
    statusUrl: "https://status.cartesia.ai/",
    fetcherType: "statuspage",
  },
  {
    id: "kimi",
    name: "Kimi",
    statusUrl: "https://status.moonshot.cn/",
    fetcherType: "statuspage",
  },
  {
    id: "luma",
    name: "Luma",
    statusUrl: "https://status.lumalabs.ai/",
    fetcherType: "betterstack",
  },
  {
    id: "vercel",
    name: "Vercel",
    category: "cloud",
    statusUrl: "https://www.vercel-status.com/",
    fetcherType: "statuspage",
  },
  {
    id: "railway",
    name: "Railway",
    category: "cloud",
    statusUrl: "https://status.railway.com/",
    fetcherType: "railway",
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    category: "cloud",
    statusUrl: "https://www.cloudflarestatus.com/",
    fetcherType: "statuspage",
  },
  {
    id: "render",
    name: "Render",
    category: "cloud",
    statusUrl: "https://status.render.com/",
    fetcherType: "statuspage",
  },
  {
    id: "fly",
    name: "Fly.io",
    category: "cloud",
    statusUrl: "https://status.flyio.net/",
    fetcherType: "statuspage",
  },
  {
    id: "netlify",
    name: "Netlify",
    category: "cloud",
    statusUrl: "https://www.netlifystatus.com/",
    fetcherType: "statuspage",
  },
  {
    id: "digitalocean",
    name: "DigitalOcean",
    category: "cloud",
    statusUrl: "https://status.digitalocean.com/",
    fetcherType: "statuspage",
  },
  {
    id: "google-cloud",
    name: "Google Cloud",
    category: "cloud",
    statusUrl: "https://status.cloud.google.com/",
    fetcherType: "google_cloud",
  },
  {
    id: "aws",
    name: "AWS",
    category: "cloud",
    statusUrl: "https://health.aws.amazon.com/health/status",
    fetcherType: "none",
  },
  {
    id: "azure",
    name: "Azure",
    category: "cloud",
    statusUrl: "https://azure.microsoft.com/status/",
    fetcherType: "none",
  },
  {
    id: "heroku",
    name: "Heroku",
    category: "cloud",
    statusUrl: "https://status.salesforce.com/products/Heroku",
    fetcherType: "heroku",
  },
  {
    id: "linode",
    name: "Linode",
    category: "cloud",
    statusUrl: "https://status.linode.com/",
    fetcherType: "statuspage",
  },
  {
    id: "fastly",
    name: "Fastly",
    category: "cloud",
    statusUrl: "https://www.fastlystatus.com/",
    fetcherType: "none",
  },
  {
    id: "bunny",
    name: "bunny.net",
    category: "cloud",
    statusUrl: "https://status.bunny.net/",
    fetcherType: "statuspage",
  },
  {
    id: "deno",
    name: "Deno Deploy",
    category: "cloud",
    statusUrl: "https://denostatus.com/",
    fetcherType: "instatus",
  },
  {
    id: "koyeb",
    name: "Koyeb",
    category: "cloud",
    statusUrl: "https://status.koyeb.com/",
    fetcherType: "instatus",
  },
  {
    id: "modal",
    name: "Modal",
    category: "cloud",
    statusUrl: "https://status.modal.com/",
    fetcherType: "betterstack",
  },
  {
    id: "firebase",
    name: "Firebase",
    category: "cloud",
    statusUrl: "https://status.firebase.google.com/",
    fetcherType: "google_cloud",
  },
  {
    id: "akamai",
    name: "Akamai",
    category: "cloud",
    statusUrl: "https://www.akamaistatus.com/",
    fetcherType: "statuspage",
  },
  {
    id: "vultr",
    name: "Vultr",
    category: "cloud",
    statusUrl: "https://status.vultr.com/",
    fetcherType: "vultr",
  },
  {
    id: "scaleway",
    name: "Scaleway",
    category: "cloud",
    statusUrl: "https://status.scaleway.com/",
    fetcherType: "statuspage",
  },
  {
    id: "oracle-cloud",
    name: "Oracle Cloud",
    category: "cloud",
    statusUrl: "https://ocistatus.oraclecloud.com/",
    fetcherType: "oracle_cloud",
  },
  {
    id: "hetzner",
    name: "Hetzner",
    category: "cloud",
    statusUrl: "https://status.hetzner.com/",
    fetcherType: "hetzner",
  },
  {
    id: "northflank",
    name: "Northflank",
    category: "cloud",
    statusUrl: "https://status.northflank.com/",
    fetcherType: "instatus",
  },
  {
    id: "lambda",
    name: "Lambda",
    category: "cloud",
    statusUrl: "https://status.lambda.ai/",
    fetcherType: "statuspage",
  },
  {
    id: "cursor",
    name: "Cursor",
    category: "developer",
    statusUrl: "https://status.cursor.com/",
    fetcherType: "statuspage",
  },
  {
    id: "devin",
    name: "Devin",
    category: "developer",
    statusUrl: "https://status.devin.ai/",
    fetcherType: "statuspage",
  },
  {
    id: "github",
    name: "GitHub",
    category: "developer",
    statusUrl: "https://www.githubstatus.com/",
    fetcherType: "statuspage",
  },
  {
    id: "gitlab",
    name: "GitLab",
    category: "developer",
    statusUrl: "https://status.gitlab.com/",
    fetcherType: "status_io",
  },
  {
    id: "circleci",
    name: "CircleCI",
    category: "developer",
    statusUrl: "https://status.circleci.com/",
    fetcherType: "statuspage",
  },
  {
    id: "npm",
    name: "npm",
    category: "developer",
    statusUrl: "https://status.npmjs.org/",
    fetcherType: "statuspage",
  },
  {
    id: "docker",
    name: "Docker",
    category: "developer",
    statusUrl: "https://www.dockerstatus.com/",
    fetcherType: "statuspage",
  },
  {
    id: "linear",
    name: "Linear",
    category: "developer",
    statusUrl: "https://linearstatus.com/",
    fetcherType: "statuspage",
  },
  {
    id: "sourcegraph",
    name: "Sourcegraph",
    category: "developer",
    statusUrl: "https://sourcegraphstatus.com/",
    fetcherType: "statuspage",
  },
  {
    id: "warp",
    name: "Warp",
    category: "developer",
    statusUrl: "https://status.warp.dev/",
    fetcherType: "statuspage",
  },
  {
    id: "bitbucket",
    name: "Bitbucket",
    category: "developer",
    statusUrl: "https://bitbucket.status.atlassian.com/",
    fetcherType: "statuspage",
  },
  {
    id: "buildkite",
    name: "Buildkite",
    category: "developer",
    statusUrl: "https://www.buildkitestatus.com/",
    fetcherType: "statuspage",
  },
  {
    id: "pypi",
    name: "PyPI",
    category: "developer",
    statusUrl: "https://status.python.org/",
    fetcherType: "statuspage",
  },
  {
    id: "rubygems",
    name: "RubyGems",
    category: "developer",
    statusUrl: "https://status.rubygems.org/",
    fetcherType: "statuspage",
  },
  {
    id: "maven",
    name: "Maven Central",
    category: "developer",
    statusUrl: "https://status.maven.org/",
    fetcherType: "statuspage",
  },
  {
    id: "postman",
    name: "Postman",
    category: "developer",
    statusUrl: "https://status.postman.com/",
    fetcherType: "statuspage",
  },
  {
    id: "augment",
    name: "Augment",
    category: "developer",
    statusUrl: "https://status.augmentcode.com/",
    fetcherType: "statuspage",
  },
  {
    id: "factory",
    name: "Factory",
    category: "developer",
    statusUrl: "https://status.factory.ai/",
    fetcherType: "statuspage",
  },
  {
    id: "tabnine",
    name: "Tabnine",
    category: "developer",
    statusUrl: "https://status.tabnine.com/",
    fetcherType: "statuspage",
  },
  {
    id: "zed",
    name: "Zed",
    category: "developer",
    statusUrl: "https://status.zed.dev/",
    fetcherType: "instatus",
  },
  {
    id: "lovable",
    name: "Lovable",
    category: "developer",
    statusUrl: "https://status.lovable.dev/",
    fetcherType: "statuspage",
  },
  {
    id: "bolt",
    name: "Bolt",
    category: "developer",
    statusUrl: "https://status.bolt.new/",
    fetcherType: "statuspage",
  },
  {
    id: "replit",
    name: "Replit",
    category: "developer",
    statusUrl: "https://status.replit.com/",
    fetcherType: "none",
  },
  {
    id: "travis",
    name: "Travis CI",
    category: "developer",
    statusUrl: "https://www.traviscistatus.com/",
    fetcherType: "statuspage",
  },
  {
    id: "semaphore",
    name: "Semaphore",
    category: "developer",
    statusUrl: "https://status.semaphore.io/",
    fetcherType: "statuspage",
  },
  {
    id: "harness",
    name: "Harness",
    category: "developer",
    statusUrl: "https://status.harness.io/",
    fetcherType: "statuspage",
  },
  {
    id: "codefresh",
    name: "Codefresh",
    category: "developer",
    statusUrl: "https://status.codefresh.io/",
    fetcherType: "statuspage",
  },
  {
    id: "crates",
    name: "crates.io",
    category: "developer",
    statusUrl: "https://status.crates.io/",
    fetcherType: "statuspage",
  },
  {
    id: "expo",
    name: "Expo",
    category: "developer",
    statusUrl: "https://status.expo.dev/",
    fetcherType: "statuspage",
  },
  {
    id: "cloudsmith",
    name: "Cloudsmith",
    category: "developer",
    statusUrl: "https://status.cloudsmith.com/",
    fetcherType: "statuspage",
  },
  {
    id: "supabase",
    name: "Supabase",
    category: "data",
    statusUrl: "https://status.supabase.com/",
    fetcherType: "statuspage",
  },
  {
    id: "neon",
    name: "Neon",
    category: "data",
    statusUrl: "https://neonstatus.com/",
    fetcherType: "status_io",
  },
  {
    id: "planetscale",
    name: "PlanetScale",
    category: "data",
    statusUrl: "https://www.planetscalestatus.com/",
    fetcherType: "statuspage",
  },
  {
    id: "convex",
    name: "Convex",
    category: "data",
    statusUrl: "https://status.convex.dev/",
    fetcherType: "statuspage",
  },
  {
    id: "upstash",
    name: "Upstash",
    category: "data",
    statusUrl: "https://status.upstash.com/",
    fetcherType: "statuspage",
  },
  {
    id: "redis",
    name: "Redis",
    category: "data",
    statusUrl: "https://status.redis.io/",
    fetcherType: "none",
  },
  {
    id: "pinecone",
    name: "Pinecone",
    category: "data",
    statusUrl: "https://status.pinecone.io/",
    fetcherType: "statuspage",
  },
  {
    id: "mongodb",
    name: "MongoDB",
    category: "data",
    statusUrl: "https://status.mongodb.com/",
    fetcherType: "statuspage",
  },
  {
    id: "cockroach",
    name: "CockroachDB",
    category: "data",
    statusUrl: "https://status.cockroachlabs.cloud/",
    fetcherType: "statuspage",
  },
  {
    id: "prisma",
    name: "Prisma",
    category: "data",
    statusUrl: "https://www.prisma-status.com/",
    fetcherType: "statuspage",
  },
  {
    id: "snowflake",
    name: "Snowflake",
    category: "data",
    statusUrl: "https://status.snowflake.com/",
    fetcherType: "statuspage",
  },
  {
    id: "databricks",
    name: "Databricks",
    category: "data",
    statusUrl: "https://status.databricks.com/",
    fetcherType: "status_io",
  },
  {
    id: "clickhouse",
    name: "ClickHouse",
    category: "data",
    statusUrl: "https://status.clickhouse.com/",
    fetcherType: "statuspage",
  },
  {
    id: "elastic",
    name: "Elastic",
    category: "data",
    statusUrl: "https://status.elastic.co/",
    fetcherType: "statuspage",
  },
  {
    id: "aiven",
    name: "Aiven",
    category: "data",
    statusUrl: "https://status.aiven.io/",
    fetcherType: "statuspage",
  },
  {
    id: "influxdb",
    name: "InfluxDB",
    category: "data",
    statusUrl: "https://status.influxdata.com/",
    fetcherType: "statuspage",
  },
  {
    id: "couchbase",
    name: "Couchbase",
    category: "data",
    statusUrl: "https://status.couchbase.com/",
    fetcherType: "statuspage",
  },
  {
    id: "confluent",
    name: "Confluent",
    category: "data",
    statusUrl: "https://status.confluent.cloud/",
    fetcherType: "statuspage",
  },
  {
    id: "tinybird",
    name: "Tinybird",
    category: "data",
    statusUrl: "https://status.tinybird.co/",
    fetcherType: "statuspage",
  },
  {
    id: "zilliz",
    name: "Zilliz",
    category: "data",
    statusUrl: "https://status.zilliz.com/",
    fetcherType: "statuspage",
  },
  {
    id: "materialize",
    name: "Materialize",
    category: "data",
    statusUrl: "https://status.materialize.com/",
    fetcherType: "statuspage",
  },
  {
    id: "turso",
    name: "Turso",
    category: "data",
    statusUrl: "https://status.turso.tech/",
    fetcherType: "betterstack",
  },
  {
    id: "qdrant",
    name: "Qdrant",
    category: "data",
    statusUrl: "https://status.qdrant.io/",
    fetcherType: "betterstack",
  },
  {
    id: "meilisearch",
    name: "Meilisearch",
    category: "data",
    statusUrl: "https://status.meilisearch.com/",
    fetcherType: "betterstack",
  },
  {
    id: "algolia",
    name: "Algolia",
    category: "data",
    statusUrl: "https://status.algolia.com/",
    fetcherType: "none",
  },
  {
    id: "redpanda",
    name: "Redpanda",
    category: "data",
    statusUrl: "https://status.redpanda.com/",
    fetcherType: "statuspage",
  },
  {
    id: "surreal",
    name: "SurrealDB",
    category: "data",
    statusUrl: "https://status.surrealdb.com/",
    fetcherType: "betterstack",
  },
  {
    id: "yugabyte",
    name: "Yugabyte",
    category: "data",
    statusUrl: "https://status.yugabyte.cloud/",
    fetcherType: "statuspage",
  },
  {
    id: "tidb",
    name: "TiDB",
    category: "data",
    statusUrl: "https://status.tidbcloud.com/",
    fetcherType: "statuspage",
  },
  {
    id: "datastax",
    name: "DataStax",
    category: "data",
    statusUrl: "https://status.datastax.com/",
    fetcherType: "none",
  },
] as const

function seedCategory(service: { id: string }): string {
  return "category" in service && typeof service.category === "string"
    ? service.category
    : "ai"
}

export async function seedServices(pool: pg.Pool): Promise<void> {
  for (const service of SERVICE_SEED) {
    await pool.query(
      `INSERT INTO services (id, name, category, status_url, fetcher_type)
       VALUES ($1, $2, $3, $4, $5)
       ON CONFLICT (id) DO UPDATE
         SET name = EXCLUDED.name,
             category = EXCLUDED.category,
             status_url = EXCLUDED.status_url,
             fetcher_type = EXCLUDED.fetcher_type,
             updated_at = now()`,
      [
        service.id,
        service.name,
        seedCategory(service),
        service.statusUrl,
        "fetcherType" in service ? service.fetcherType : "none",
      ],
    )
  }
}
